language: lisp

sudo: required

env:
  matrix:
    - LISP=sbcl COVERALLS=true
    - LISP=allegro
    - LISP=cmucl

matrix:
  allow_failures:
    - env: LISP=cmucl
    - env: LISP=allegro

install:
  - curl -L https://github.com/luismbo/cl-travis/raw/master/install.sh | sh

os:
  - osx
  - linux

notifications:
  email: false

script:
  - cl -l fiveam -l cl-coveralls
       -e '(setf fiveam:*debug-on-error* t
                 fiveam:*debug-on-failure* t)'
       -e '(setf *debugger-hook*
                  (lambda (c h)
                    (declare (ignore c h))
                    (uiop:quit -1)))'
       -e '(coveralls:with-coveralls (:exclude (list "cl-phys-test.lisp"))
             (ql:quickload :cl-phys.math)
             (ql:quickload :cl-phys.fitting)
             (ql:quickload :cl-phys)
             (ql:quickload :cl-phys-test))'
