language: lisp

sudo: required

env:
  matrix:
    - LISP=sbcl COVERALLS=true
    - LISP=allegro
    - LISP=cmucl

matrix:
  allow_failures:
    - env: LISP=cmucl
    - env: LISP=allegro

install:
  - curl -L https://github.com/luismbo/cl-travis/raw/master/install.sh | sh
  - git clone https://github.com/fukamachi/cl-coveralls.git ~/lisp/cl-coveralls

os:
  - osx
  - linux

notifications:
  email: false

script:
  - cl -e '(setf *debugger-hook*
                  (lambda (c h)
                    (declare (ignore c h))
                    (uiop:quit -1)))'
       -e '(in-package :cl-user)'
       -e '#+sbcl (ql:quickload :cl-coveralls)'
       -e '(ql:quickload :cl-phys-test)'
       -e '#+sbcl (coveralls:with-coveralls (:exclude (list "cl-phys-test.lisp"))
                    (cl-phys-test:run-all-tests))
       -e '#-sbcl (cl-phys-test:run-all-tests)
